[package]
edition = "2018"
name = "hyperboria"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "bin/main.rs"

[build-dependencies]
tonic-build = { version = "0.6.2", default-features = false, features = ["prost", "transport"] }

[dependencies]
clap = { version = "3.1.6", features = ["cargo"] }
colored = "2.0.0"
config = "0.12.0"
crossbeam-channel = "0.5.4"
futures = "0.3.21"
futures-util = "0.3.21"
hyper = "0.14.17"
lazy_static = "1.4.0"
num_cpus = "1.13.1"
opentelemetry = "0.17.0"
opentelemetry-prometheus = "0.10.0"
parking_lot = { version = "0.12.0", features = ["send_guard"] }
prometheus = "0.13.0"
prost = "0.9.0"
prost-types = "0.9.0"
rand = "0.8.5"
rdkafka = "0.28.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
serde_yaml = "0.8.23"
signal-hook = "0.3.13"
tantivy = { version = "0.17.0", features = ["brotli-compression"] }
tantivy-fst = "0.3.0"
textwrap = "0.15.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full", "time"] }
tonic = "0.6.2"
tower = "0.4.12"
tower-http = { version = "0.2.5", features = ["set-header", "trace"] }
tracing = "0.1.32"
tracing-appender = "0.2.2"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "json"] }

[workspace.metadata.raze]
default_gen_buildrs = true
genmode = "Remote"
package_aliases_dir = "cargo"
rust_rules_workspace_name = "rules_rust"
targets = [
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]
workspace_path = "//rules/rust"

[package.metadata.raze.crates.json5.'*']
data_attr = "glob([\"**/*.pest\"])"